# SPDX-License-Identifier: EUPL-1.2

# Labeler configuration
# Each label must have an array of file patterns it applies to

"type":
  - fix":
    - "src/**/*.py"
    - "lib/**/*.py"
    - "**/bugfix/**"

"type: feature":
  - "src/**/*.py"
  - "lib/**/*.py"
  - "**/feature/**"

"type: docs":
  - "docs/**/*.md"
  - "**/README.md"
  - "**/CONTRIBUTING.md"
  - "**/*.rst"

"type: test":
  - "tests/**/*.py"
  - "**/test/**"
  - "**/test_*.py"

"status: work-in-progress":
  - "**/WIP/**"

"status: ready-for-review":
  - "**/RFR/**"

"security":
  - "src/security/**/*.py"
  - "**/auth/**"
  - "**/oauth/**"

"breaking":
  - "**/*.py"
  - "docs/release-notes/**/*.md"

"deprecation":
  - "**/*.py"
  - "docs/deprecations/**/*.md"

"size/xs": []
"size/s": []
"size/m": []
"size/l": []
"size/xl": []
