# SPDX-License-Identifier: MIT

# Labeler configuration
# Applies labels to pull requests based on the files they modify or other rules

labels:
  # Core types based on file changes
  "type: fix":
    - "src/**/*.py"
    - "lib/**/*.py"
    - "**/bugfix/**"

  "type: feature":
    - "src/**/*.py"
    - "lib/**/*.py"
    - "**/feature/**"

  "type: docs":
    - "docs/**/*.md"
    - "**/README.md"
    - "**/CONTRIBUTING.md"
    - "**/*.rst"

  "type: test":
    - "tests/**/*.py"
    - "**/test/**"
    - "**/test_*.py"

  # Status labels
  "status: work-in-progress":
    - "**/WIP/**"

  "status: ready-for-review":
    - "**/RFR/**"

  # Security and other sensitive changes
  "security":
    - "src/security/**/*.py"
    - "**/auth/**"
    - "**/oauth/**"

  "breaking":
    - "**/*.py"
    - "docs/release-notes/**/*.md"

  "deprecation":
    - "**/*.py"
    - "docs/deprecations/**/*.md"

  # PR size labels based on the workflow step
  "size/xs": []
  "size/s": []
  "size/m": []
  "size/l": []
  "size/xl": []
