# SPDX-License-Identifier: EUPL-1.2

# Type Labels
type-fix:
  - any:
    - "src/**/*.py"
    - "lib/**/*.py"
    - "**/bugfix/**"
    - "**/hotfix/**"
    - "**/patch/**"

type-feature:
  - any:
    - "src/**/*.py"
    - "lib/**/*.py"
    - "**/feature/**"
    - "**/feat/**"
    - "**/enhancement/**"
type-docs:
  - any:
    - "docs/**/*"
    - "**/*.md"
    - "**/*.rst"
    - "**/*.txt"
    - "mkdocs.yml"
    - "**/*.ipynb"

type-test:
  - any:
    - "tests/**/*.py"
    - "**/test/**"
    - "**/tests/**"
    - "**/*_test.py"
    - "**/test_*.py"
    - "**/testing/**"
    - "**/*.spec.py"

type-chore:
  - any:
    - "**/build/**"
    - "**/ci/**"
    - "**/config/**"
    - "**/scripts/**"
    - ".github/**/*"
    - ".gitignore"
    - ".editorconfig"
    - "LICENSE*"
    - "NOTICE*"

type-refactor:
  - any:
    - "src/**/*.py"
    - "lib/**/*.py"
    - "**/refactor/**"
    - "**/cleanup/**"

type-style:
  - any:
    - "**/*.css"
    - "**/*.scss"
    - "**/*.sass"
    - "**/*.less"
    - "**/*.html"
    - "**/*.jinja"
    - "**/*.j2"
    - ".style.yapf"
    - ".pylintrc"
    -  "pyproject.toml"
    - "setup.cfg"

type-performance:
  - any:
    - "src/**/*.py"
    - "lib/**/*.py"
    - "**/perf/**"
    - "**/benchmark/**"
    - "**/optimizations/**"

# Status Labels
status/work-in-progress:
  - any:
    - "**/WIP/**"
    - "**/draft/**"

status/ready-for-review:
  - any:  
    - "**/RFR/**"
    - "**/ready/**"

status/blocked:
  - any: 
    - "**/blocked/**"
    - "**/hold/**"

status/needs-discussion:
  - any:  
    - "**/discuss/**"
    - "**/proposal/**"
    - "RFC.md"

# Security Labels
security:
  - any:  
    - "src/security/**/*.py"
    - "**/auth/**"
    - "**/oauth/**"
    - "**/crypto/**"
    - "**/password/**"
    - "**/permission/**"
    - "**/secret/**"
    - "**/*security*/**"

# Breaking Changes
breaking:
  - any:  
    - "**/*.py"
    - "**/*.pyi"
    - "**/*.pyx"
    - "**/*.pxd"
    - "docs/breaking-changes/**"
    - "docs/migrations/**"
    - "docs/upgrades/**"

# Deprecation
deprecation:
  - any:  
    - "**/*.py"
    - "**/*.pyi"
    - "**/*.pyx"
    - "**/*.pxd"
    - "docs/deprecations/**"

# CI/CD
ci:
  - any:  
    - ".github/workflows/**"
    - ".github/actions/**"
    - ".gitlab-ci.yml"
    - "azure-pipelines.yml"
    - "Jenkinsfile"
    - ".travis.yml"
    - ".circleci/**"

# Dependencies
# SPDX-License-Identifier: EUPL-1.2

# Type Labels
type-fix:
  - any:
    - "src/**/*.py"
    - "lib/**/*.py"
    - "**/bugfix/**"
    - "**/hotfix/**"
    - "**/patch/**"

type-feature:
  - any:
    - "src/**/*.py"
    - "lib/**/*.py"
    - "**/feature/**"
    - "**/feat/**"
    - "**/enhancement/**"
type-docs:
  - any:
    - "docs/**/*"
    - "**/*.md"
    - "**/*.rst"
    - "**/*.txt"
    - "mkdocs.yml"
    - "**/*.ipynb"

type-test:
  - any:
    - "tests/**/*.py"
    - "**/test/**"
    - "**/tests/**"
    - "**/*_test.py"
    - "**/test_*.py"
    - "**/testing/**"
    - "**/*.spec.py"

type-chore:
  - any:
    - "**/build/**"
    - "**/ci/**"
    - "**/config/**"
    - "**/scripts/**"
    - ".github/**/*"
    - ".gitignore"
    - ".editorconfig"
    - "LICENSE*"
    - "NOTICE*"

type-refactor:
  - any:
    - "src/**/*.py"
    - "lib/**/*.py"
    - "**/refactor/**"
    - "**/cleanup/**"

type-style:
  - any:
    - "**/*.css"
    - "**/*.scss"
    - "**/*.sass"
    - "**/*.less"
    - "**/*.html"
    - "**/*.jinja"
    - "**/*.j2"
    - ".style.yapf"
    - ".pylintrc"
    -  "pyproject.toml"
    - "setup.cfg"

type-performance:
  - any:
    - "src/**/*.py"
    - "lib/**/*.py"
    - "**/perf/**"
    - "**/benchmark/**"
    - "**/optimizations/**"

# Status Labels
status/work-in-progress:
  - any:
    - "**/WIP/**"
    - "**/draft/**"

status/ready-for-review:
  - any:  
    - "**/RFR/**"
    - "**/ready/**"

status/blocked:
  - any: 
    - "**/blocked/**"
    - "**/hold/**"

status/needs-discussion:
  - any:  
    - "**/discuss/**"
    - "**/proposal/**"
    - "RFC.md"

# Security Labels
security:
  - any:  
    - "src/security/**/*.py"
    - "**/auth/**"
    - "**/oauth/**"
    - "**/crypto/**"
    - "**/password/**"
    - "**/permission/**"
    - "**/secret/**"
    - "**/*security*/**"

# Breaking Changes
breaking:
  - any:  
    - "**/*.py"
    - "**/*.pyi"
    - "**/*.pyx"
    - "**/*.pxd"
    - "docs/breaking-changes/**"
    - "docs/migrations/**"
    - "docs/upgrades/**"

# Deprecation
deprecation:
  - any:  
    - "**/*.py"
    - "**/*.pyi"
    - "**/*.pyx"
    - "**/*.pxd"
    - "docs/deprecations/**"

# CI/CD
ci:
  - any:  
    - ".github/workflows/**"
    - ".github/actions/**"
    - ".gitlab-ci.yml"
    - "azure-pipelines.yml"
    - "Jenkinsfile"
    - ".travis.yml"
    - ".circleci/**"

# Dependencies
dependencies:
  - any:  
    - "requirements*.txt"
    - "requirements/**"
    - "poetry.lock"
    - "pyproject.toml"
    - "setup.py"
    - "setup.cfg"
    - "Pipfile*"
    - "conda-env.yml"
    - ".pre-commit-config.yaml"

# Infrastructure
infrastructure:
  - any:  
    - "terraform/**"
    - "ansible/**"
    - "kubernetes/**"
    - "k8s/**"
    - "docker/**"
    - "Dockerfile*"
    - "docker-compose*.yml"
    - "helm/**"
    - "deployment/**"
    - "scripts/**"

# Documentation
documentation:
  - any:  
    - "docs/**/*"
    - "**/*.md"
    # '**/*.adoc'
    - "**/*.rst"
    - "**/*.txt"
    - "mkdocs.yml"
    - "**/*.ipynb"
    - "examples/**"
    - "samples/**"
    - "tutorials/**"

# Testing
testing:
  - tests/**/*
  - pytest.ini
  - conftest.py

# Add 'ci' label to any change in CI configuration
ci:
  - .github/workflows/*
  - .github/actions/*

# Add 'security' label to any change in security-related files
security:
  - security/**/*
  - '**/*security*.md'
 
# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
'source':
  - changed-files:
      - any-glob-to-any-file: src/**/*
      - all-globs-to-all-files: '!src/docs/**'
# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
'feature':
  - head-branch: [^feature, feature]
# Add 'release' label to any PR that is opened against the `main` branch
release:
  - base-branch: release
