name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'
      - 'dep'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ here too

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'maintenance'
  default: patch

template: |
  ## Changes

  $CHANGES

  ## 👨‍💻 Contributors

  $CONTRIBUTORS

  ## 🔗 Links

  - [PyPI](https://pypi.org/project/jmbde/)
  - [Documentation](https://jmbde-python.readthedocs.io/)