---
# SPDX-FileCopyrightText: GitHub, Inc. and contributors
# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://json.schemastore.org/release-drafter.json

name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION

categories:
  - title: 🚀 Features
    labels:
      - type: feature
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - type: fix
      - fix
      - bug
  - title: 🔒 Security Updates
    labels:
      - type: security
      - security
  - title: ⚡ Performance Improvements
    labels:
      - type: performance
      - performance
  - title: 📚 Documentation Updates
    labels:
      - type: docs
      - documentation
  - title: 🧪 Testing
    labels:
      - type: test
      - testing
  - title: 🔧 Maintenance
    labels:
      - type: maintenance
      - maintenance
      - chore
  - title: 📦 Dependency Updates
    labels:
      - type: dependencies
      - dependencies
      - dep-upgrade

change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'

version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - type: feature
  patch:
    labels:
      - type: fix
      - type: maintenance
      - type: docs
      - type: dependencies
      - type: security

exclude-labels:
  - skip-changelog
  - status: work-in-progress

template: |
  ## 🚀 What's Changed

  $CHANGES

  ## 📦 Dependency Updates
  $CHANGES_BY_LABELS.dependencies

  ## 🤝 Contributors
  Thanks to our contributors:
  $CONTRIBUTORS

  ## Installation Instructions
  To install this version:
  ```bash
  pip install jmbde-python==$RESOLVED_VERSION
