---
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '⚡ Performance'
    labels:
      - 'performance'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '🔧 Maintenance'
    labels:
      - 'maintenance'
      - 'chore'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

version-resolver:
  major:
    labels:
      - "type: breaking"
  minor:
    labels:
      - "type: feature"
  patch:
    labels:
      - "type: bug"
      - "type: maintenance"
      - "type: docs"
      - "type: dependencies"
      - "type: security"

exclude-labels:
  - "skip-changelog"

template: |
  ## What's Changed

  $CHANGES

  ## 📦 Dependencies
  $CHANGES_BY_LABELS.dependencies

  ## Contributors
  $CONTRIBUTORS

  ## Installation
  ```bash
  pip install jmbde-python==$RESOLVED_VERSION
  ```
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

no-changes-template: 'No changes included in this release'

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/*'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'feature'
    branch:
      - '/feat\/.+/'
