---
image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
tasks:
  - init: |
      pip3 install poetry
      poetry install
    name: Split terminal
  - openMode: split-right
    command: echo SplitTerminal && clear
vscode:
  extensions:
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
