---
# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

# Devskim
REPOSITORY_DEVSKIM_ARGUMENTS:
  - --config=.github/devskim-config.json

# Python-specific settings
PYTHON_MYPY_ARGUMENTS:
  - --config-file=pyproject.toml

PYTHON_BANDIT_ARGUMENTS:
  - -c
  - pyproject.toml

PYTHON_ISORT_ARGUMENTS:
  - --profile=black

PYTHON_PYLINT_ARGUMENTS:
  - --rcfile=pyproject.toml
  - --output-format=colorized

# EditorConfig
EDITORCONFIG_FILTER_REGEX_EXCLUDE: (LICENSES/|LICENSE|license\.md)
# Markdown-Linter
MARKDOWN_FILTER_REGEX_EXCLUDE: (LICENSES/|LICENSE|license\.md)
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json
MARKDOWN_MARKDOWNLINT_ARGUMENTS:
  - --fix

# JSon-Linter
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (\.vscode/|\.devcontainer/devcontainer.json)
JSON_V8R_FILTER_REGEX_EXCLUDE: (\.devcontainer/devcontainer.json|\.vscode/)

# JSCpd (Duplicate Code Detection)
JSCODE_JSCODE_DUPLICATION_ARGUMENTS:
  - --exclude=LICENSES/
  - --exclude=.*\.md$
  - --exclude=src/jmbde/ui/ui_*
  - --exclude=docs/comuminity/contributing.md
  - --exclude=docs/comuminity/code_of_conduct.md

# SPELL
SPELL_CSPELL_FILTER_REGEX_EXCLUDE: (docs/de|docs/es|docs/it|LICENSE)
# SPELL_LYCHEE_FILTER_REGEX_EXCLUDE:
# SPELL_VALE_FILTER_REGEX_INCLUDE: (README.md)

# TYPESCRIPT
TYPESCRIPT_FILTER_REGEX_EXCLUDE: (resources/translations)

# PRE-Commands
PRE_COMMANDS:
  - command: vale sync
  - command: npm install pnpm -D
  - command: pnpm install
