---
# SPDX-License-Identifier: EUPL-1.2
# SPDX-FileCopyrightText: 2023-present Jürgen Mülbert <juergen.muelbert@outlook.de>
#
#
# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - CLOUDFORMATION
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  # - CSS
  - EDITORCONFIG
  # - SPELL # Uncomment to disable checks of spelling mistakes
  # - JAVASCRIPT
  - TEKTON
DISABLE_LINTERS:
  # - JSON_PRETTIER
  # - MARKDOWN_MARKDOWN_LINK_CHECK
  - PYTHON_PYRIGHT
  # - REPOSITORY_GITLEAKS
  # - REPOSITORY_KICS
  # - SPELL_PROSELINT
  # - SPELL_MISSPELL
  # - SPELL_VALE
  - SQL_TSQLLINT
DISABLE_ERRORS_LINTERS:
  # - PYTHON_BANDIT
  - REPOSITORY_DEVSKIM
  # - REPOSITORY_GRYPE
  # - REPOSITORY_SEMGREP
  - REPOSITORY_TRUFFLEHOG
  # - SPELL_LYCHEE
PRINT_ALL_FILES: false
FILTER_REGEX_EXCLUDE: '(\.venv|pnpm-lock\.yaml)'
# JSON-Linter
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (\.vscode/|\.devcontainer/devcontainer.json)
JSON_V8R_FILTER_REGEX_EXCLUDE: (\.secretlintrc.json|\.devcontainer/devcontainer.json|\.vscode/|\.github/linters/valestyles/)
# YAML
YAML_FILTER_REGEX_EXCLUDE: (\.github/linters/valestyles/)
# TODO: #1181 Prettier, MkDocs and Github Labeler has more schema in the Schema Store Y8RR can't handle this
YAML_V8R_FILTER_REGEX_EXCLUDE: (\.grype\.yaml|\.hound\.yml|\.github/invite-contributors\.yml|\.checkov\.yml|\.devcontainer/docker-compose\.yml|\.github/dependency-review-config\.yml|\.github/release-drafter\.yml|\.github/linters/valestyles/)
# BASH
BASH_FILTER_REGEX_EXCLUDE: "(lib)"
# Markdown
MARKDOWN_FILTER_REGEX_EXCLUDE: (LICENSES/|LICENSE|license\.md)
# MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
# SPELL
SPELL_VALE_FILE_EXTENSIONS:
  - .md
SPELL_FILTER_REGEX_EXCLUDE: (valestyles|\.github|docs/licenses)
# DOCKER
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3016 --ignore DL3018 --ignore DL3028 --ignore DL3059 --ignore DL4001 --ignore DL4006 --ignore SC2015 --ignore SC2016 --ignore SC2039 --ignore SC2086 --ignore SC1091 --ignore SC3046"
# TRIVY
REPOSITORY_TRIVY_ARGUMENTS:
  - "--skip-dirs"
  - ".automation/test"
  - "--skip-dirs"
  - ".venv"
# EditorConfig
EDITORCONFIG_FILTER_REGEX_EXCLUDE: (LICENSES/|LICENSE|license\.md)
# TYPESCRIPT
TYPESCRIPT_FILTER_REGEX_EXCLUDE: (assets/translations)
# GENERAL
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: true
EMAIL_REPORTER: false
FILEIO_REPORTER: false
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: false
# Run npm install before linting
PRE_COMMANDS:
  - command: echo "Installing dependencies from package.json..."
  - command: npm install
