---
# MegaLinter Configuration File
# See all available variables at https://megalinter.io/configuration/

APPLY_FIXES: all
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
DISABLE_LINTERS:
  - SPELL_CSPELL
  - SPELL_MISSPELL

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
UPDATED_SOURCES_REPORTER: true
TEXT_REPORTER: true
SARIF_REPORTER: true

PYTHON_BLACK_ARGUMENTS:
  - "--config=pyproject.toml"

PYTHON_PYLINT_ARGUMENTS:
  - "--rcfile=.pylintrc"

PYTHON_ISORT_ARGUMENTS:
  - "--settings-file=.isort.cfg"

MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml

DISABLE_ERRORS_IF_LESS_THAN: 0

REPORT_OUTPUT_FOLDER: megalinter-reports