---
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "16"

# Build documentation with Mkdocs
mkdocs:
  configuration: mkdocs.yml

# Dependencies required to build your docs
python:
  install:
    - requirements: requirements.txt
