# V8R Configuration
# This configuration file specifies the validation settings for the V8R linter.

# - One or more filenames or glob patterns describing local file or files to validate
# - overridden by passing one or more positional arguments
patterns:
  - "*json"

# - Level of verbose logging. 0 is standard, higher numbers are more verbose
# - overridden by passing --verbose / -v
# - default = 0
verbose: 0

# - Exit with code 0 even if an error was encountered. True means a non-zero exit code is only issued if validation
#   could be completed successfully and one or more files were invalid
# - overridden by passing --ignore-errors
# - default = false
ignoreErrors: true

# - Remove cached HTTP responses older than cacheTtl seconds old.
#   Specifying 0 clears and disables cache completely
# - overridden by passing --cache-ttl
# - default = 600
cacheTtl: 86400

# - Output format for validation results
# - overridden by passing --format
# - default = text
format: json

# - A custom schema catalog.
#   This catalog will be searched ahead of any custom catalogs passed using
#   --catalogs or SchemaStore.org
customCatalog:
  schemas:
    - name: Custom Schema # The name of the schema (required)
      description: Custom Schema # A description of the schema (optional)
      # A Minimatch glob expression for matching up file names with a schema (required)
      fileMatch:
        - "*.geojson"
      # A URL or local file path for the schema location (required)
      location: foo/bar/geojson-schema.json
      # A custom parser to use for files matching fileMatch instead of trying to infer the correct parser from the filename (optional)
      parser: json5
