---
# SPDX-License-Identifier: BSD-3-Clause
# yamllint configuration file
extends: default

# Ignore specific directories and files
ignore:
  - .cache/
  - .direnv/
  - .venv/
  - .flatpak/
  - .flatpak/builder/
  - build*/
  - repo/
  - node_modules/
  - .github/linters/valestyles/Microsoft/
  - .github/linters/valestyles/proselint/
  - .vscode/
  - pnpm-lock.yaml
  - package-lock.json

rules:
  # Formatting rules
  line-length:
    max: 120 # Matches Prettier's printWidth for YAML
    level: warning
  indentation:
    spaces: 2 # Consistent with editorconfig and Prettier
    level: error
  trailing-spaces:
    level: error # Disallow trailing spaces
  empty-lines:
    max: 2 # Allow up to 2 empty lines for readability
    level: warning
  new-lines:
    type: unix # Enforce LF endings to align with editorconfig and Prettier
    level: error

  # Quotation rules
  quoted-strings:
    required: only-when-needed # Avoid unnecessary quoting
    extra-allowed: ["{|}", "|"]
    level: warning

  # Key and value rules
  key-duplicates:
    level: error # Prevent duplicate keys
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
    level: error
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    level: error

  # Block formatting
  braces:
    max-spaces-inside: 1 # Ensure clean formatting
    level: error
  hyphens:
    max-spaces-after: 1 # Space after list indicators
    level: error

  # Document structure
  document-start:
    present: true # Enforce document start `---`
    level: warning
  document-end:
    present: false # Do not require document end `...`
    level: warning

  # Advanced rules
  octal-values:
    forbid-implicit-octal: true
    level: error
  comments:
    min-spaces-from-content: 1 # Prettier-compliant spacing
    level: warning
  truthy:
    level: warning # Warn about non-boolean values for better YAML compatibility
