---
version: '0.2'
files:
  - '**/*'
dictionaries:
  - bash
  - docker
  - dict-python
ignorePaths:
  - s**/node_modules/**
  - '**/vscode-extension/**'
  - '**/.git/**'
  - '.github/actions/**'
  - '.github/workflows/**'
  - 'docs/api-docs/**'
  - 'cspell.config.yaml'
  - '.codespell.rc'
  - '*.gz'
  - '*.lock'
  - '*.svg'
  - '.gitignore'
  - '.devcontainer/.dockerignore'
  - '.vscode'
  - 'megalinter'
  - 'package-lock.json'
  - 'report'
  - 'npm-lock.yaml'
  - 'dist/**'
  - 'build/**'
  - 'out/**'
useGitignore: true
language: en, en-GB, de, de-DE
allowCompoundWords: true
enableGlobDot: true
words:
  - ahmadnassri
  - Akismet
  - aarch
  - asdict
  - Authentiq
  - cjolowicz
  - codecov
  - cython
  - envrc
  - furo
  - Gitaly
  - GPLV
  - HADOLINT
  - idiv
  - itertools 
  - ipynb
  - isort
  - jmbde
  - jmuelbert
  - jquery
  - Kantive
  - kondo
  - mkdocs
  - Mülbert
  - msvs
  - mymodule
  - MSYS
  - mypackage
  - mypy
  - noxfile
  - nojekyll
  - paren
  - pautodoc
  - pycache
  - pygtk
  - PyLint
  - pylint
  - PYPI
  - PYRIGHT
  - pytest
  - pyupgrade
  - rdiv  
  - rgxs
  - runit
  - Sidekiq
  - Signup
  - TEKTON
  - tkinter  
  - TRIVY
  - venv
  - VIRTUALENVS
  - xdoctest
  - xrange
  - xreadlines  
