---
# SPDX-FileCopyRightText: 2023-2024 Jürgen Mülbert <juergen.muelbert@outlook.de>
#
# SPDX-License-Identifier: EUPL-1.2
# yaml-lint: ignore line-length
# yaml-language-server: schema=https://json.schemastore.org/mkdocs-1.6.json
# $schema=https://json.schemastore.org/mkdocs-1.6.json

site_name: JM BDE
site_url: https://jmuelbert.github.io/jmbde-python/
site_description: JM BDE - Management of inventory and computer equipment
site_author: Jürgen Mülbert

repo_name: jmuelbert/jmbde-python
repo_url: https://github.com/jmuelbert/jmbde-python
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2023-2024 Jürgen Mülbert

docs_dir: docs
site_dir: site

theme:
  name: material
  custom_dir: docs/.overrides
  language: en
  favicon: assets/images/logo.svg
  font:
    text: Source Sans Pro
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
    logo: material/check-network-outline
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - search:
      separator: '[\\s\\-,:!=\\[\\]()"/]+|(?!=[^=])'
  - glightbox
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - mike:
      alias_type: copy
      canonical_version: latest
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_root_full_path: false
            show_if_no_docstring: true
            show_signature_annotations: true
            show_bases: false
            docstring_style: google
            docstring_section_style: table
  - git-revision-date-localized:
      type: datetime
      timezone: Europe/Berlin
      enable_creation_date: true
      fallback_to_build_date: true
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: JM BDE Documentation
        - locale: de
          name: Deutsch
          build: true
          site_name: JM BDE Dokumentation
  - mermaid2
  - git-revision-date-localized:
      type: datetime
      timezone: Europe/Berlin
      enable_creation_date: true
      fallback_to_build_date: true

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
    - name: Italiano
      link: /it/
      lang: it
    - name: Español
      link: /es/
      lang: es

nav:
  - English:
      - en/index.md
      - en/installation.md
    # ... other English pages
  - Deutsch:
      - de/index.md
      - de/installation.md
    # ... other German pages
  - Italiano:
      - it/index.md
      - it/installation.md
    # ... other Italian pages
  - Español:
      - es/index.md
      - es/installation.md
