# SPDX-FileCopyRightText: 2023 J端rgen M端lbert <juergen.muelbert@web.de>
#
# SPDX-License-Identifier: EUPL-1.2
#
# Python configuration file for building, dependencies, and tooling.
#
# For more information, visit
# https://snarky.ca/what-the-heck-is-pyproject-toml/.

[tool.poetry]
name = "jmbde-python"
version = "0.1.0"
description = "A bde written with python an tkinter"
authors = ["J端rgen M端lbert <juergen.muelbert@web.de>"]
documentation = "http://github.com/jmuelbert//jmbde-python"
keywords = ["jmbde_python", "tkinter", "python3", "poetry"]
license = "EUPL-1.2"
readme = "README.md"

packages = [{include = "jmbde", from = "src"}, ]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.7"

[tool.poetry.group.dev.dependencies]
Pygments = ">=2.10.0"
black = ">=21.10b0"
coverage = {extras = ["toml"], version = ">=6.2"}
darglint = ">=1.8.1"
flake8 = ">=4.0.1"
flake8-bandit = ">=2.1.2"
flake8-bugbear = ">=21.9.2"
flake8-docstrings = ">=1.6.0"
flake8-rst-docstrings = ">=0.2.5"
furo = "^2024.8.6"
isort = "^5.13.2"
mypy = "^1.11"
pep8-naming = "^0.14.1"
pre-commit = "^3.8.0"
pre-commit-hooks = "^4.6.0"
pytest = "^8.3.2"
pyupgrade = "^3.17.0"
safety = "^3.2.7"
sphinx = "^7.4"
sphinx-autobuild = "^2024.4.16"
typeguard = "^4.1.5"
xdoctest = {extras = ["colors"], version = ">=0.15.10"}
myst-parser = "^3.0.1"

[tool.poetry.scripts]
jmbde_python = "jmbde.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["jmbde", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.isort]
profile = "black"
force_single_line = true
lines_after_imports = 2

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
