[project]
name = "jmopenorders"
version = "0.2.0"
description = "A BDE tool"
authors = [
    "Jürgen Mülbert <juergen.muelbert@gmail.com>"
]
license = "EUPL-1.2"
readme = "README.rst"
python = "^3.6"
homepage = "https://jmbde-python.github.io/"
repository = "https://github.com/jmuelbert/jmbde-python"
documentation =  "https://readthedocs.org/projects/jmuelbert/jmbde-python"

keywords = []

classifiers = [
        "Intended Audience:: End Users/Desktop",
        "Intended Audience:: Developers",
        "License:: OSI Approved:: European Union Public Licence 1.2 (EUPL 1.2)",
        "Natural Language:: English",
        "Operating System:: OS Independent",
        "Operating System:: MacOS:: MacOS X",
        "Operating System:: POSIX",
        "Operating System:: POSIX:: BSD",
        "Operating System:: POSIX:: Linux",
        "Operating System:: Microsoft:: Windows",
        "Programming Language:: Python",
        "Programming Language:: Python:: 3",
        "Programming Language:: Python:: 3:: Only",
        "Programming Language:: Python:: 3.6",
        "Programming Language:: Python:: 3.7",
        "Programming Language:: Python:: Implementation:: CPython",
        "Programming Language :: Python :: Implementation :: PyPy",
        "Development Status:: 4 - Beta",
        "Environment:: Console",
        "Topic:: Office / Business",
]

# Requirements
[dependencies]
PySide2="^5.12.5"
pip="^19.0.1"

[dev-dependencies]
black = { version = "^18,3-alpha.0", python = "^3.6" }
[build-system]
# Minimum requirements for the build system to execute.
# See https://github.com/scipy/scipy/pull/10431 for the AIX issue.
requires = [
    "setuptools >= 40.0.4",
    "setuptools_scm >= 2.0.0, <3",
    "wheel >= 0.29.0",
]
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 88
target_version = ['py36']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
