# Poetry pyproject.toml: https://python-poetry.org/docs/pyproject

[tool.poetry]
name = "jmbde"
version = "0.2.2"
description = "A BDE tool"
authors = ["Jürgen Mülbert <juergen.muelbert@gmail.com>"]
license = "GPL-3.0"
readme = "README.rst"
homepage = "https://github.com/jmuelbert/jmbde-python"
repository = "https://github.com/jmuelbert/jmbde-python"
documentation = "https://jmbde-python.readthedocs.io"
packages = [
    { include = "jmbde", from = "src" }
]

# Keywords description https://python-poetry.org/docs/pyproject/#keywords
keywords = ["jmbde", "jmbde-python", "business", "BDE", "datebase" ]

# Pypi classifiers: https://pypi.org/classifiers/
classifiers=[
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: End Users/Desktop",
  "License :: OSI Approved :: GNU Public License 3.0 (GPL-3.0)",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Office/Business",
]

[tool.poetry.urls]
Changelog = "https://github.com/jmuelbert/jmbde-python/releases"

[tool.poetry.dependencies]
python = ">=3.6.5, <3.11"
click = "^8.0.4"
PySide6 = "^6.2"


[tool.poetry.dev-dependencies]
coverage = {extras = ["toml"], version = "^6.2"}
pytest = "^7.0.1"
safety = "^1.10.3"
mypy = "^0.931"
typeguard = "^2.13.3"
xdoctest = {extras = ["colors"], version = "^0.15.10"}
sphinx-autobuild = "^2021.3.14"
pre-commit = "^2.17.0"
black = "^22.1"
flake8 = "^4.0.1"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^22.3.20"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.5"
pep8-naming = "^0.12.1"
darglint = "^1.8.1"
reorder-python-imports = "^2.6.0"
pre-commit-hooks = "^4.1.0"
faker = "^13.3.0"
openpyxl = "^3.0.5"
Sphinx = "^4.3.2"
Pygments = "^2.11.2"
pyupgrade = "^2.31.0"
furo = ">=2021.11.12"


[tool.poetry.scripts]
# Entry points for the package https://python-poetry.org/docs/pyproject/#scripts
jmbde = "jmbde.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["jmbde"]

[tool.coverage.report]
show_missing = true
fail_under = 12

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[[tool.mypy.overrides]]
module = "jmbde.gui.forms.*"
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
