---
# Feature Request
# This template is for feature requests. Please fill out as much information as possible.
# yaml-language-server: $schema= https://json.schemastore.org/github-issue-template-1.0.0.json
# The name of the issue template
# SPDX-License-Identifier: CC4.0-BY-SA-4.0
# SPDX-FileCopyrightText: 2023 - 2024 Jürgen Mülbert <juergen.muelbert@outlook.de>
#
# The name of the issue template
name: Feature Request
description: Request for a missing or a new Feature.
title: "[Request]: "
labels: [request]
assignees:
  - jmuelbert
body:
  - type: markdown
    attributes:
      value: |
        Thank you for getting in touch! Please fill out this form as completely as possible.

        Want to report a bug instead? [Use our bug report form](https://github.com/jmuelbert/jmbde-python/issues/new?assignees=&labels=&projects=&template=01-bug-report.yml)
  - type: input
    id: jmbde-python-version
    attributes:
      label: What version of `jmbde-python` are you using?
      placeholder: 0.0.0
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: What is your idea?
      description: A brief, one or two sentence description of your idea for a new feature.
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Why is this feature necessary?
      description: Explain why this feature is important. What problems would it solve? Which users would it help?
    validations:
      required: true
  - type: textarea
    id: prior-art
    attributes:
      label: Do you have examples of this feature in other projects?
      description: Help us understand your idea by sharing links to example implementations we can compare against.
      placeholder: |
        - Example
        - Example
        - Example
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      description: Let us know if your interested in contributing this feature yourself.
      options:
        - label: I am willing to submit a pull request for this feature.
          required: false
