---
# SPDX-FileCopyrightText: GitHub, Inc. and contributors
# SPDX-License-Identifier: MIT
#
# Automatically edits an issue's descriptions with a header,
# one of:
#
# - Bug report
# - Crash report
# - Feature or enhancement

name: Add issue header

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  add-header:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # V7.0.1
        with:
          # language=JavaScript
          script: |
            // https://devguide.python.org/triage/labels/#type-labels
            const ISSUE_TYPES = {
              'type-bug': 'Bug report',
              'type-crash': 'Crash report',
              'type-feature': 'Feature or enhancement'
            };
            
            try {
              const { data: issue } = await 
              github.rest.issues.get({
                ...context.repo,
                issue_number: context.issue.number
              });
            
              const matchedLabel = issue.labels
                .map(label => typeof label === 'string' ? label : label.name)
                .find(labelName => labelName in ISSUE_TYPES);

              if (matchedLabel) {
                const header = ISSUE_TYPES[matchedLabel];
                console.log(`Adding header: ${header}`);
                
                await github.rest.issues.update({
                  ...context.repo,
                  issue_number: context.issue.number,
                  body: `# ${header}\n\n${issue.body?.replaceAll('\r', '') || ''}`
                });
              } else {
                console.log('No matching issue type label found');
              }
            } catch (error) {
              core.setFailed(`Action failed: ${error.message}`);
            }
