---
# SPDX-FileCopyrightText: Codacy Analysis CLI GitHub Action Group
#
# SPDX-License-Identifier: Apache-2.0
#
# This workflow checks out code, performs a Codacy security scan
#
# and integrates the results with the
# GitHub Advanced Security code scanning feature.  For more information on
# the Codacy security scan action usage and parameters, see
# https://github.com/codacy/codacy-analysis-cli-action.
# For more information on Codacy Analysis CLI in general, see
# https://github.com/codacy/codacy-analysis-cli.
name: Codacy Security Scan
on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/*.md'
      
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/*.md'

  schedule:
    - cron: '0 12 * * 1' # Run at 12:00 UTC every Monday

permissions: read-all

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  codacy-security-scan:
    if: |
      github.actor != 'dependabot[bot]' &&
      !contains(github.event.head_commit.message, '[skip ci]')
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    permissions:
      contents: read
      security-events: write
      actions: read
      
    steps:
      - name: 🔒 Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
          
      - name: 🧰 Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 1
          
      - name: 🔍 Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@3ff8e64eb4b714c4bee91b7b4eea31c6fc2c4f93 # v4.3.0
        with:
          verbose: true
          output: results/codacy-results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
          # project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: 📤 Upload SARIF Results
        if: always()
        uses: github/codeql-action/upload-sarif@b7cec7526559c32f1616476ff32d17ba4c59b2d6 # v3.25.5
        with:
          sarif_file: results/codacy-results.sarif
          category: Codacy-Security

      - name: 🧹 Cleanup
        if: always()
        run: |
          rm -rf results/
